name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test
  benchmarks-and-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: benches
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt --check
      - name: Run clippy
        run: cargo clippy --all-targets -- --deny warnings
      - name: Run benchmarks
        run: cargo bench
